USE
webbshop_db;

insert into Category (name)
values ('Kängor'),
       ('Sneakers'),
       ('Sandaler'),
       ('Löparskor'),
       ('Stövlar'),
       ('Badskor'),
       ('Herrskor'),
       ('Läderskor');

insert into Shoe (brand, name, colour, size, price, stock, category_id)
values ('Lundhags', 'Trekking Boot', 'Padje Light', 42, 5299.99, 10,
        ( select category_id from Category where name = 'Kängor' )),
       ('Lundhags', 'Trekking Boot', 'Padje Light', 45, 5299.99, 7,
        ( select category_id from Category where name = 'Kängor' )),
       ('Lundhags', 'Trekking Boot', 'Padje Dark', 39, 5299.99, 10,
        ( select category_id from Category where name = 'Kängor' )),
       ('Lundhags', 'Trail Boot', 'Tived', 42, 3249.99, 2,
        ( select category_id from Category where name = 'Kängor' )),
       ('Meindl', 'Capri', 'Ljusbrun', 45, 1699.00, 4,
        ( select category_id from Category where name = 'Läderskor' )),
       ('Meindl', 'Capri', 'Ljusbrun', 42, 1699.00, 2,
        ( select category_id from Category where name = 'Läderskor' )),
       ('Meindl', 'Ascona Identity', 'Mörkbrun', 42, 3499.00, 6,
        ( select category_id from Category where name = 'Läderskor' )),
       ('Nike', 'Alpha Fly 3', 'Neongrön', 45, 2137.00, 2,
        ( select category_id from Category where name = 'Löparskor' )),
       ('Nike', 'Alpha Fly 3', 'Rosa och vit', 45, 2137.00, 2,
        ( select category_id from Category where name = 'Löparskor' )),
       ('Nike', 'Alpha Fly 3', 'Marinblå', 45, 2137.00, 2,
        ( select category_id from Category where name = 'Löparskor' )),
       ('Birkenstock', 'Shinjuku', 'Basalt Grey', 45, 2650.00, 3,
        ( select category_id from Category where name = 'Sandaler' )),
       ('Birkenstock', 'Shinjuku 2 Strap', 'Black', 43, 2650.00, 2,
        ( select category_id from Category where name = 'Sandaler' )),
       ('Birkenstock', 'Arizona', 'Dark Brown', 45, 1100.00, 10,
        ( select category_id from Category where name = 'Sandaler' )),
       ('Adidas', 'Adilette', 'Blue/White', 45, 389.99, 6,
        ( select category_id from Category where name = 'Badskor' )),
       ('Adidas', 'Adilette Ayoon', 'Beige', 40, 464.00, 8,
        ( select category_id from Category where name = 'Badskor' )),
       ('Adidas', 'Campus', 'Core-black/Off-white', 45, 869.00, 10,
        ( select category_id from Category where name = 'Sneakers' )),
       ('Timberland', 'Stone street', 'Wheat', 41, 2246.00, 9,
        ( select category_id from Category where name = 'Stövlar' ));